In [34]:
import pandas as pd
import numpy as np
import sklearn

In [35]:
data_processed = pd.read_csv('Abscentism_data.csv', index_col = False)
data_processed.head()

Unnamed: 0  Result_1  Result_2  Result_3  Result_4  Transportation Expense  \
0           0         0         0         0         1                     289   
1           1         0         0         0         0                     118   
2           2         0         0         0         1                     179   
3           3         1         0         0         0                     279   
4           4         0         0         0         1                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month_value  Day_of_the_Week  
0         2     1                          4            7                1  
1         1     0                          0            7                1  
2         0     0                          2            7                2  
3         2     0                          4            7                3  
4         2     1                          2            7                3

In [36]:
data_processed = data_processed.drop('Unnamed: 0', axis=1)

In [37]:
data_processed.head()

Result_1  Result_2  Result_3  Result_4  Transportation Expense  \
0         0         0         0         1                     289   
1         0         0         0         0                     118   
2         0         0         0         1                     179   
3         1         0         0         0                     279   
4         0         0         0         1                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month_value  Day_of_the_Week  
0         2     1                          4            7                1  
1         1     0                          0            7                1  
2         0     0                          2            7                2  
3         2     0                          4            7                3  
4         2     1                          2            7                3

# Perform a logistic regression to predict Abscenteeism 

# Create targets

In [38]:
# Using the Abscenteeism time in hour, classify the hour into excessive hour or normal
data_processed['Absenteeism Time in Hours'].median()

3.0

In [39]:
targets = np.where(data_processed['Absenteeism Time in Hours'] > data_processed['Absenteeism Time in Hours'].median(),1, 0)

In [40]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [41]:
data_processed['Excessive Abscenteeism'] = targets

In [42]:
data_processed.head()

Result_1  Result_2  Result_3  Result_4  Transportation Expense  \
0         0         0         0         1                     289   
1         0         0         0         0                     118   
2         0         0         0         1                     179   
3         1         0         0         0                     279   
4         0         0         0         1                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month_value  Day_of_the_Week  \
0         2     1                          4            7                1   
1         1     0                          0            7                1   
2         0     0                          2            7                2   
3         2     0                          4            7                3   
4         2     1                          2            7                3   

   Excessive Abscenteeism  
0                       1  
1                       0  
2                       0  
3                       1  
4                       0

In [43]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [44]:
data_with_targets = data_processed.drop('Absenteeism Time in Hours', axis=1)

In [45]:
data_with_targets.head()

Result_1  Result_2  Result_3  Result_4  Transportation Expense  \
0         0         0         0         1                     289   
1         0         0         0         0                     118   
2         0         0         0         1                     179   
3         1         0         0         0                     279   
4         0         0         0         1                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Month_value  Day_of_the_Week  Excessive Abscenteeism  
0         2     1            7                1                       1  
1         1     0            7                1                       0  
2         0     0            7                2                       0  
3         2     0            7                3                       1  
4         2     1            7                3                       0

In [46]:
data_processed is data_with_targets

False

# Select Regression input

In [47]:
data_with_targets.iloc[ :, : -1]

Result_1  Result_2  Result_3  Result_4  Transportation Expense  \
0           0         0         0         1                     289   
1           0         0         0         0                     118   
2           0         0         0         1                     179   
3           1         0         0         0                     279   
4           0         0         0         1                     289   
..        ...       ...       ...       ...                     ...   
695         1         0         0         0                     179   
696         1         0         0         0                     225   
697         1         0         0         0                     330   
698         0         0         0         1                     235   
699         0         0         0         1                     291   

     Distance to Work  Age  Daily Work Load Average  Body Mass Index  \
0                  36   33                  239.554               30   
1                  13   50                  239.554               31   
2                  51   38                  239.554               31   
3                   5   39                  239.554               24   
4                  36   33                  239.554               30   
..                ...  ...                      ...              ...   
695                22   40                  237.656               22   
696                26   28                  237.656               24   
697                16   28                  237.656               25   
698                16   32                  237.656               25   
699                31   40                  237.656               25   

     Education  Children  Pets  Month_value  Day_of_the_Week  
0            0         2     1            7                1  
1            0         1     0            7                1  
2            0         0     0            7                2  
3            0         2     0            7                3  
4            0         2     1            7                3  
..         ...       ...   ...          ...              ...  
695          1         2     0            5                2  
696          0         1     2            5                2  
697          1         0     0            5                3  
698          1         0     0            5                3  
699          0         1     1            5                3  

[700 rows x 14 columns]

In [48]:
Unscaled_input = data_with_targets.iloc[ :, : -1]

# Standardize data

In [52]:
from sklearn.preprocessing import StandardScaler

abscentism_scalar = StandardScaler()
# Create Scalar object

In [54]:
abscentism_scalar.fit(Unscaled_input) # Scaling mechanism

StandardScaler()

In [55]:
Scaled_input = abscentism_scalar.transform(Unscaled_input) # Apply the scaling mechanism

In [56]:
Scaled_input

array([[-0.57735027, -0.09298136, -0.31448545, ...,  0.26848661,
         0.18272635, -0.68370352],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
         0.18272635, -0.68370352],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
         0.18272635, -0.00772546],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ..., -0.58968976,
        -0.3882935 ,  0.66825259],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
        -0.3882935 ,  0.66825259],
       [-0.57735027, -0.09298136, -0.31448545, ...,  0.26848661,
        -0.3882935 ,  0.66825259]])

In [58]:
Scaled_input.shape

(700, 14)

# Split the data into train & test and shuffle

In [59]:
from sklearn.model_selection import train_test_split

# SPlit

In [60]:
train_test_split(Scaled_input, targets)

[array([[ 1.73205081, -0.09298136, -0.31448545, ...,  1.12666297,
          0.18272635,  0.66825259],
        [-0.57735027, -0.09298136,  3.17979734, ..., -0.58968976,
          0.7537462 , -0.68370352],
        [ 1.73205081, -0.09298136, -0.31448545, ...,  0.26848661,
          1.32476605, -0.00772546],
        ...,
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.58968976,
          1.03925612,  2.69618675],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
         -0.10278357, -1.35968157],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
          0.7537462 , -0.68370352]]),
 array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.58968976,
         -0.10278357, -1.35968157],
        [-0.57735027, -0.09298136, -0.31448545, ...,  0.26848661,
          1.03925612, -0.00772546],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.58968976,
          1.03925612,  1.34423065],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ..., -

In [71]:
X_train, X_test, Y_train, Y_test = train_test_split(Scaled_input, targets, train_size=0.8, random_state= 20)

In [69]:
X_train.shape, Y_train.shape

((560, 14), (560,))

In [70]:
X_test.shape, Y_test.shape

((140, 14), (140,))

# Modelling

# Logistic regression with Sklearn

In [72]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

# Train the model

In [73]:
reg = LogisticRegression()
reg.fit(X_train, Y_train)

LogisticRegression()

In [74]:
reg.score(X_train, Y_train)

0.7839285714285714

Manaully check accuracy

In [76]:
model_output = reg.predict(X_train)
model_output

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [78]:
Y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [79]:
model_output == Y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [80]:
np.sum(model_output == Y_train) #Total number of true value

439

In [83]:
model_output.shape[0]

560

In [84]:
np.sum(model_output == Y_train) / model_output.shape[0]

0.7839285714285714

# Finding Coefficients and intercepts

In [85]:
reg.coef_

array([[ 2.07458229,  0.33454073,  1.56073174,  1.32776177,  0.70640686,
        -0.03937135, -0.20039574, -0.00427805,  0.31904773, -0.13505278,
         0.38185537, -0.33342255,  0.18829573, -0.07090252]])

In [86]:
reg.intercept_

array([-0.22178284])

In [89]:
Unscaled_input.columns.values

array(['Result_1', 'Result_2', 'Result_3', 'Result_4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month_value', 'Day_of_the_Week'], dtype=object)

In [90]:
Featured_names = Unscaled_input.columns.values

In [96]:
Summary_table = pd.DataFrame(columns = ['Features'], data = Featured_names)
Summary_table["Coeficients"] = np.transpose(reg.coef_) #(Transposed bcos by defualt ndarray are rows not colums)
Summary_table

Features  Coeficients
0                  Result_1     2.074582
1                  Result_2     0.334541
2                  Result_3     1.560732
3                  Result_4     1.327762
4    Transportation Expense     0.706407
5          Distance to Work    -0.039371
6                       Age    -0.200396
7   Daily Work Load Average    -0.004278
8           Body Mass Index     0.319048
9                 Education    -0.135053
10                 Children     0.381855
11                     Pets    -0.333423
12              Month_value     0.188296
13          Day_of_the_Week    -0.070903

In [97]:
Summary_table

Features  Coeficients
0                  Result_1     2.074582
1                  Result_2     0.334541
2                  Result_3     1.560732
3                  Result_4     1.327762
4    Transportation Expense     0.706407
5          Distance to Work    -0.039371
6                       Age    -0.200396
7   Daily Work Load Average    -0.004278
8           Body Mass Index     0.319048
9                 Education    -0.135053
10                 Children     0.381855
11                     Pets    -0.333423
12              Month_value     0.188296
13          Day_of_the_Week    -0.070903

In [98]:
Summary_table.index = Summary_table.index + 1
Summary_table.loc[0] = ['intercept', reg.intercept_[0]]
Summary_table = Summary_table.sort_index()

In [99]:
Summary_table

Features  Coeficients
0                 intercept    -0.221783
1                  Result_1     2.074582
2                  Result_2     0.334541
3                  Result_3     1.560732
4                  Result_4     1.327762
5    Transportation Expense     0.706407
6          Distance to Work    -0.039371
7                       Age    -0.200396
8   Daily Work Load Average    -0.004278
9           Body Mass Index     0.319048
10                Education    -0.135053
11                 Children     0.381855
12                     Pets    -0.333423
13              Month_value     0.188296
14          Day_of_the_Week    -0.070903

# Interpreting Coefficients