In [14]:
import pandas as pd
import numpy as np
import sklearn

In [15]:
data_processed = pd.read_csv('Abscentism_data.csv', index_col = False)
data_processed.head()

Unnamed: 0  Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  \
0           0         0         0         0         1                     289   
1           1         0         0         0         0                     118   
2           2         0         0         0         1                     179   
3           3         1         0         0         0                     279   
4           4         0         0         0         1                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  
0         2     1                          4            7                1  
1         1     0                          0            7                1  
2         0     0                          2            7                2  
3         2     0                          4            7                3  
4         2     1                          2            7                3

In [16]:
data_processed = data_processed.drop('Unnamed: 0', axis=1)

In [17]:
data_processed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  \
0         0         0         0         1                     289   
1         0         0         0         0                     118   
2         0         0         0         1                     179   
3         1         0         0         0                     279   
4         0         0         0         1                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  
0         2     1                          4            7                1  
1         1     0                          0            7                1  
2         0     0                          2            7                2  
3         2     0                          4            7                3  
4         2     1                          2            7                3

# Perform a logistic regression to predict Abscenteeism 

# Create targets

In [18]:
# Using the Abscenteeism time in hour, classify the hour into excessive hour or normal
data_processed['Absenteeism Time in Hours'].median()

3.0

In [19]:
targets = np.where(data_processed['Absenteeism Time in Hours'] > data_processed['Absenteeism Time in Hours'].median(),1, 0)

In [20]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [21]:
data_processed['Excessive Abscenteeism'] = targets

In [22]:
data_processed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  \
0         0         0         0         1                     289   
1         0         0         0         0                     118   
2         0         0         0         1                     179   
3         1         0         0         0                     279   
4         0         0         0         1                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  Absenteeism Time in Hours  Month Value  Day of the Week  \
0         2     1                          4            7                1   
1         1     0                          0            7                1   
2         0     0                          2            7                2   
3         2     0                          4            7                3   
4         2     1                          2            7                3   

   Excessive Abscenteeism  
0                       1  
1                       0  
2                       0  
3                       1  
4                       0

In [23]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [24]:
data_with_targets = data_processed.drop(['Absenteeism Time in Hours','Distance to Work', 'Day of the Week',
       'Daily Work Load Average'], axis=1)

In [25]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  Age  \
0         0         0         0         1                     289   33   
1         0         0         0         0                     118   50   
2         0         0         0         1                     179   38   
3         1         0         0         0                     279   39   
4         0         0         0         1                     289   33   

   Body Mass Index  Education  Children  Pets  Month Value  \
0               30          0         2     1            7   
1               31          0         1     0            7   
2               31          0         0     0            7   
3               24          0         2     0            7   
4               30          0         2     1            7   

   Excessive Abscenteeism  
0                       1  
1                       0  
2                       0  
3                       1  
4                       0

In [26]:
data_processed is data_with_targets

False

# Select Regression input

In [27]:
data_with_targets.iloc[ :, : -1]

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  Age  \
0           0         0         0         1                     289   33   
1           0         0         0         0                     118   50   
2           0         0         0         1                     179   38   
3           1         0         0         0                     279   39   
4           0         0         0         1                     289   33   
..        ...       ...       ...       ...                     ...  ...   
695         1         0         0         0                     179   40   
696         1         0         0         0                     225   28   
697         1         0         0         0                     330   28   
698         0         0         0         1                     235   32   
699         0         0         0         1                     291   40   

     Body Mass Index  Education  Children  Pets  Month Value  
0                 30          0         2     1            7  
1                 31          0         1     0            7  
2                 31          0         0     0            7  
3                 24          0         2     0            7  
4                 30          0         2     1            7  
..               ...        ...       ...   ...          ...  
695               22          1         2     0            5  
696               24          0         1     2            5  
697               25          1         0     0            5  
698               25          1         0     0            5  
699               25          0         1     1            5  

[700 rows x 11 columns]

In [28]:
Unscaled_input = data_with_targets.iloc[ :, : -1]

# Standardize data

In [29]:
from sklearn.preprocessing import StandardScaler

abscentism_scalar = StandardScaler()
# Create Scalar object

In [30]:
abscentism_scalar.fit(Unscaled_input) # Scaling mechanism

StandardScaler()

In [31]:
Unscaled_input

Reason_1  Reason_2  Reason_3  Reason_4  Transportation Expense  Age  \
0           0         0         0         1                     289   33   
1           0         0         0         0                     118   50   
2           0         0         0         1                     179   38   
3           1         0         0         0                     279   39   
4           0         0         0         1                     289   33   
..        ...       ...       ...       ...                     ...  ...   
695         1         0         0         0                     179   40   
696         1         0         0         0                     225   28   
697         1         0         0         0                     330   28   
698         0         0         0         1                     235   32   
699         0         0         0         1                     291   40   

     Body Mass Index  Education  Children  Pets  Month Value  
0                 30          0         2     1            7  
1                 31          0         1     0            7  
2                 31          0         0     0            7  
3                 24          0         2     0            7  
4                 30          0         2     1            7  
..               ...        ...       ...   ...          ...  
695               22          1         2     0            5  
696               24          0         1     2            5  
697               25          1         0     0            5  
698               25          1         0     0            5  
699               25          0         1     1            5  

[700 rows x 11 columns]

In [32]:
Scaled_input = abscentism_scalar.transform(Unscaled_input) # Apply the scaling mechanism

In [33]:
Scaled_input

array([[-0.57735027, -0.09298136, -0.31448545, ...,  0.88046927,
         0.26848661,  0.18272635],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.01928035,
        -0.58968976,  0.18272635],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.91902997,
        -0.58968976,  0.18272635],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ..., -0.91902997,
        -0.58968976, -0.3882935 ],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.91902997,
        -0.58968976, -0.3882935 ],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.01928035,
         0.26848661, -0.3882935 ]])

In [34]:
Scaled_input

array([[-0.57735027, -0.09298136, -0.31448545, ...,  0.88046927,
         0.26848661,  0.18272635],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.01928035,
        -0.58968976,  0.18272635],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.91902997,
        -0.58968976,  0.18272635],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ..., -0.91902997,
        -0.58968976, -0.3882935 ],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.91902997,
        -0.58968976, -0.3882935 ],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.01928035,
         0.26848661, -0.3882935 ]])

# Split the data into train & test and shuffle

In [35]:
from sklearn.model_selection import train_test_split

# SPlit

In [36]:
train_test_split(Scaled_input, targets)

[array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.91902997,
         -0.58968976,  0.18272635],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.91902997,
         -0.58968976, -1.24482327],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.91902997,
         -0.58968976, -0.95931334],
        ...,
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.01928035,
         -0.58968976, -0.3882935 ],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.01928035,
         -0.58968976,  0.18272635],
        [-0.57735027, -0.09298136, -0.31448545, ...,  0.88046927,
         -0.58968976,  0.7537462 ]]),
 array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.01928035,
         -0.58968976, -0.95931334],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.01928035,
         -0.58968976,  0.18272635],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.01928035,
          1.12666297, -1.24482327],
        ...,
        [ 1.73205081, -0.09298136, -0.31448545, ..., -

In [37]:
X_train, X_test, Y_train, Y_test = train_test_split(Scaled_input, targets, train_size=0.8, random_state= 20)

In [38]:
X_train.shape, Y_train.shape

((560, 11), (560,))

In [39]:
X_test.shape, Y_test.shape

((140, 11), (140,))

# Modelling

# Logistic regression with Sklearn

In [40]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

# Train the model

In [41]:
reg = LogisticRegression()
reg.fit(X_train, Y_train)

LogisticRegression()

In [42]:
reg.score(X_train, Y_train)

0.7839285714285714

Manaully check accuracy

In [43]:
model_output = reg.predict(X_train)
model_output

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [44]:
Y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [45]:
model_output == Y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [46]:
np.sum(model_output == Y_train) #Total number of true value

439

In [47]:
model_output.shape[0]

560

In [48]:
np.sum(model_output == Y_train) / model_output.shape[0]

0.7839285714285714

# Finding Coefficients and intercepts

In [49]:
reg.coef_

array([[ 2.07060602,  0.33597918,  1.56203203,  1.31392372,  0.69080918,
        -0.19858992,  0.32509576, -0.12584894,  0.37082428, -0.32495752,
         0.18468965]])

In [50]:
reg.intercept_

array([-0.22415067])

In [51]:
Unscaled_input.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Month Value'], dtype=object)

In [52]:
Featured_names = Unscaled_input.columns.values

In [53]:
Summary_table = pd.DataFrame(columns = ['Features'], data = Featured_names)
Summary_table["Coeficients"] = np.transpose(reg.coef_) #(Transposed bcos by defualt ndarray are rows not colums)
Summary_table

Features  Coeficients
0                 Reason_1     2.070606
1                 Reason_2     0.335979
2                 Reason_3     1.562032
3                 Reason_4     1.313924
4   Transportation Expense     0.690809
5                      Age    -0.198590
6          Body Mass Index     0.325096
7                Education    -0.125849
8                 Children     0.370824
9                     Pets    -0.324958
10             Month Value     0.184690

In [54]:
Summary_table

Features  Coeficients
0                 Reason_1     2.070606
1                 Reason_2     0.335979
2                 Reason_3     1.562032
3                 Reason_4     1.313924
4   Transportation Expense     0.690809
5                      Age    -0.198590
6          Body Mass Index     0.325096
7                Education    -0.125849
8                 Children     0.370824
9                     Pets    -0.324958
10             Month Value     0.184690

In [55]:
Summary_table.index = Summary_table.index + 1
Summary_table.loc[0] = ['intercept', reg.intercept_[0]]
Summary_table = Summary_table.sort_index()

In [56]:
Summary_table

Features  Coeficients
0                intercept    -0.224151
1                 Reason_1     2.070606
2                 Reason_2     0.335979
3                 Reason_3     1.562032
4                 Reason_4     1.313924
5   Transportation Expense     0.690809
6                      Age    -0.198590
7          Body Mass Index     0.325096
8                Education    -0.125849
9                 Children     0.370824
10                    Pets    -0.324958
11             Month Value     0.184690

# Test the model


In [57]:
reg.score(X_test,Y_test)

0.7357142857142858

In [59]:
predict_proba = reg.predict_proba(X_test)
predict_proba

array([[0.70811655, 0.29188345],
       [0.5721039 , 0.4278961 ],
       [0.3987536 , 0.6012464 ],
       [0.78719503, 0.21280497],
       [0.0668946 , 0.9331054 ],
       [0.3111248 , 0.6888752 ],
       [0.28565469, 0.71434531],
       [0.08108162, 0.91891838],
       [0.79928258, 0.20071742],
       [0.74973079, 0.25026921],
       [0.46768065, 0.53231935],
       [0.18458351, 0.81541649],
       [0.04095243, 0.95904757],
       [0.7555815 , 0.2444185 ],
       [0.23782308, 0.76217692],
       [0.54134575, 0.45865425],
       [0.53349868, 0.46650132],
       [0.520355  , 0.479645  ],
       [0.40543527, 0.59456473],
       [0.02764621, 0.97235379],
       [0.7015122 , 0.2984878 ],
       [0.78719503, 0.21280497],
       [0.40550972, 0.59449028],
       [0.40550972, 0.59449028],
       [0.17426979, 0.82573021],
       [0.75364779, 0.24635221],
       [0.48844947, 0.51155053],
       [0.88051837, 0.11948163],
       [0.13089896, 0.86910104],
       [0.78719503, 0.21280497],
       [0.

In [60]:
predict_proba[:,1]

array([0.29188345, 0.4278961 , 0.6012464 , 0.21280497, 0.9331054 ,
       0.6888752 , 0.71434531, 0.91891838, 0.20071742, 0.25026921,
       0.53231935, 0.81541649, 0.95904757, 0.2444185 , 0.76217692,
       0.45865425, 0.46650132, 0.479645  , 0.59456473, 0.97235379,
       0.2984878 , 0.21280497, 0.59449028, 0.59449028, 0.82573021,
       0.24635221, 0.51155053, 0.11948163, 0.86910104, 0.21280497,
       0.37722038, 0.69563785, 0.71101679, 0.55846122, 0.21280497,
       0.56307123, 0.20931063, 0.80979261, 0.41300737, 0.6300506 ,
       0.20410533, 0.42159529, 0.22729926, 0.10466249, 0.85724567,
       0.65408304, 0.70636669, 0.29188345, 0.21168449, 0.19567294,
       0.56557265, 0.07759079, 0.6888752 , 0.26925275, 0.85966686,
       0.45388672, 0.93036835, 0.21790894, 0.08520077, 0.0894016 ,
       0.70577652, 0.67746261, 0.28724979, 0.86048417, 0.1899959 ,
       0.27057335, 0.01399431, 0.20931063, 0.81221789, 0.28543027,
       0.20931063, 0.06838131, 0.92866479, 0.47804084, 0.63876

# Save the model

In [61]:
import pickle

In [62]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [ ]:
with open('scaler', 'wb') as file:
    pickle.dump(abscentism_scalar, file)